theme = "dark_plus"

[editor]
shell = ["bash", "-c"]
insert-final-newline = false

[editor.statusline]
left = ["mode", "spinner", "workspace-diagnostics", "version-control"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]

[editor.lsp]
display-inlay-hints = true

[keys.insert]
# up = "no_op"
# down = "no_op"
# left = "no_op"
# right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.normal."+"]
b = ":run-shell-command cargo build"
c = ":run-shell-command cargo clippy"
